# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

closedeBH_cpp <- function(e, alpha = 0.05, set = NULL, approximate = FALSE) {
    .Call(`_eClosure_closedeBH_cpp`, e, alpha, set, approximate)
}

